#  lightweight Python 3.11 image
FROM python:3.11-slim

# Install Java (needed for descriptor generation)
RUN apt-get update && apt-get install -y default-jre

#  Set working directory
WORKDIR /app

#  Copy your project files into the container
COPY . .

#  Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

#  Expose Flask's default port
EXPOSE 5000

# Start your Flask app
CMD ["python", "app.py"]
